GET https://localhost:44332/references/parks
Accept: application/json

POST https://localhost:44332/api/scheduledoutings
Content-Type: application/json
{
  "parkId": "string",
  "when": "2021-06-15T19:26:17.882Z",
  "who": "string",
  "notes": "string",
  "numberOfPeople": 0
}
